name: Deploy Website to AWS S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  DeployWebJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: ://amazonaws.com

      - name: Upload Files to S3 Bucket
        run: |
          # Replace 'your-bucket-name' with your actual bucket name
          aws s3 sync . s3://your-bucket-name --exclude ".git/*" --exclude ".github/*"
